site_name: Terrareg
repo_url: https://github.com/matthewjohn/terrareg
plugins:
- glightbox
theme:
  name: material
  palette:
    primary: white
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

nav:
  - Introduction:
    - index.md
    - README: MAIN.md
  - Quick Start:
    - quickstart.md
  - Deployment:
    - deployment.md
    - Upgrading: UPGRADE.md
    - diagnosing_issues.md
  - Configuration:
    - security.md
    - customising.md
    - Configuration Reference: CONFIG.md
    - API Reference: API.md
  - Modules:
    - modules/storage.md
    - modules/uploading.md
    - modules/best_practices.md
    - modules/analytics.md
    - modules/cost_analysis.md
    - modules/security_scanning.md
    - modules/misc.md
  - Providers:
    - providers/index.md
  - Development:
    - LOCAL_DEVELOPMENT.md
    - CONTRIBUTING.md

extra:
  version:
    default: latest
