site_name: Terrareg
site_url: http://localhost:5000
repo_url: https://github.com/matthewjohn/terrareg
plugins:
- glightbox
theme:
  name: material
  # logo: ./images/logo.svg
  # favicon: ./images/icon.svg
  # custom_dir: docs/overrides
  palette:
    primary: white
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

nav:
  - Introduction: index.md
  - Quick Start:
    - quickstart.md
  - Deployment:
    - UPGRADE_NOTES.md
    - LOCAL_DEVELOPMENT.md
  - Configuration:
    - CONFIG.md

extra:
  version:
    default: latest
